# Site settings
title: Noneface
email: 956905550@qq.com
baseurl: /  # the subpath of your site, e.g. /blog/
github_username:  noneface

# Build settings
markdown: redcarpet
post_limit: 10
paginate: 8
highlighter: pygments
