title: Noneface
email: nonefacesay@gmail.com
baseurl: /  # the subpath of your site, e.g. /blog/
github_username:  noneface
markdown: kramdown
paginate: 13
paginate_path: "/page:num" 
highlighter: pygments
gems: [jekyll-paginate]
comments: true
